-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jan 23, 2026 at 06:21 PM
-- Server version: 8.0.43-34
-- PHP Version: 8.2.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbbbe2e6nbidsk`
--

-- --------------------------------------------------------

--
-- Table structure for table `wp_products`
--

CREATE TABLE `wp_products` (
  `id` int NOT NULL,
  `product_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `product_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `product_short_description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expanded_description` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_products`
--

INSERT INTO `wp_products` (`id`, `product_id`, `product_name`, `product_short_description`, `expanded_description`, `created_at`, `updated_at`) VALUES
(1, '52b6518e-f888-11f0-a10b-00163e1efc06', 'Premium Wireless Headphones', 'Premium audio experience', 'Experience superior sound quality with our Premium Wireless Headphones featuring advanced active noise cancellation technology that blocks out ambient noise for an immersive listening experience. These headphones deliver crystal-clear audio with deep bass and crisp highs, perfect for music lovers and audiophiles. With an impressive 30-hour battery life, you can enjoy uninterrupted listening throughout your day without worrying about recharging. The comfortable over-ear design with soft cushioned ear cups ensures all-day comfort, while Bluetooth 5.0 connectivity provides seamless pairing with all your devices. Built-in controls allow easy volume adjustment and track selection. The foldable design makes them perfect for travel, and the included carrying case protects your investment.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(2, '52b74443-f888-11f0-a10b-00163e1efc06', 'Smart Fitness Watch', 'Advanced fitness tracking', 'Take control of your health and fitness journey with our Smart Fitness Watch that combines cutting-edge technology with stylish design. This advanced wearable features built-in GPS for accurate distance tracking during runs and cycling, a continuous heart rate monitor that provides real-time data, and comprehensive sleep tracking to help you understand your rest patterns. Monitor multiple workout modes including running, swimming, cycling, and yoga with automatic activity recognition. The vibrant touchscreen display shows notifications from your smartphone, while the water-resistant design withstands sweat and rain. Track your daily steps, calories burned, and active minutes to reach your fitness goals. With up to 7 days of battery life and smartphone compatibility, this fitness watch is your perfect training companion.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(3, '52b7e150-f888-11f0-a10b-00163e1efc06', 'Ergonomic Office Chair', 'Ultimate comfort for work', 'Transform your workspace with our Ergonomic Office Chair designed to provide ultimate comfort during long work hours while promoting proper posture and reducing back pain. This premium chair features advanced lumbar support that contours to your spine\'s natural curve, adjustable armrests that accommodate different body types and working positions, and a breathable mesh backrest that keeps you cool throughout the day. The pneumatic height adjustment allows you to find your perfect seating position, while the 360-degree swivel and smooth-rolling casters provide excellent mobility. The thick padded seat cushion uses high-density foam that maintains its shape over time. Tilt tension control lets you customize the rocking resistance, and the chair supports up to 300 lbs with its sturdy construction.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(4, '52b8717e-f888-11f0-a10b-00163e1efc06', 'Stainless Steel Water Bottle', 'Stay hydrated in style', 'Stay perfectly hydrated throughout your day with our premium Stainless Steel Water Bottle featuring advanced double-wall vacuum insulation technology that keeps cold drinks refreshingly chilled for up to 24 hours and hot beverages steaming for 12 hours. Crafted from high-grade 18/8 food-grade stainless steel, this bottle is completely BPA-free and won\'t retain flavors or odors. The wide mouth opening makes filling and cleaning effortless while accommodating ice cubes, and the leak-proof lid ensures worry-free transport in your bag. The powder-coated exterior provides a comfortable grip and prevents condensation from forming on the outside. Perfect for the gym, office, hiking, or daily commuting, this eco-friendly bottle reduces single-use plastic waste while keeping you hydrated in style.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(5, '52b8ffc6-f888-11f0-a10b-00163e1efc06', 'Yoga Mat Premium', 'Perfect for your practice', 'Elevate your yoga practice with our Premium Yoga Mat designed for yogis of all skill levels seeking superior comfort and stability. This extra-thick 6mm mat provides exceptional cushioning that protects your joints during challenging poses while remaining firm enough for proper balance and alignment. The innovative non-slip textured surface ensures a secure grip even during the most intense hot yoga sessions or sweaty workouts. Made from eco-friendly TPE material that\'s free from harmful chemicals, latex, and PVC, this mat is safe for you and the environment. The generous 72-inch length accommodates taller practitioners, and the lightweight design with included carrying strap makes transport to and from the studio effortless. Easy to clean with just soap and water.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(6, '52b99d5b-f888-11f0-a10b-00163e1efc06', 'LED Desk Lamp', 'Illuminate your workspace', 'Optimize your workspace lighting with our versatile LED Desk Lamp that combines modern design with practical functionality for enhanced productivity and reduced eye strain. This adjustable lamp features multiple brightness levels and color temperature settings, allowing you to customize the lighting for reading, working, or relaxing. The flexible gooseneck design enables precise positioning to direct light exactly where you need it most. Energy-efficient LED technology provides bright, flicker-free illumination while consuming minimal power and lasting up to 50,000 hours. The integrated USB charging port keeps your devices powered without occupying additional outlets. Touch controls make operation simple and intuitive, while the stable weighted base prevents tipping. Perfect for home offices, students, artists, and anyone seeking superior task lighting.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(7, '52ba2b7e-f888-11f0-a10b-00163e1efc06', 'Bluetooth Speaker Portable', 'Music anywhere you go', 'Take your music anywhere with our Portable Bluetooth Speaker featuring powerful 360-degree sound that fills any space with rich, balanced audio and impressive bass. This rugged speaker boasts an IPX7 waterproof rating, making it perfect for pool parties, beach outings, camping trips, and outdoor adventures without worry. The rechargeable battery delivers an impressive 12 hours of continuous playback, ensuring the music never stops. Advanced Bluetooth 5.0 technology provides seamless wireless connectivity up to 100 feet away, while the built-in microphone enables hands-free calling. Compact and lightweight with a convenient carrying strap, this speaker fits easily in backpacks or bags. Connect two speakers together for true stereo sound and enhanced volume that transforms any gathering into an unforgettable party.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(8, '52babc34-f888-11f0-a10b-00163e1efc06', 'Coffee Maker Programmable', 'Wake up to fresh coffee', 'Wake up to the enticing aroma of freshly brewed coffee with our Programmable Coffee Maker that combines convenience with exceptional brewing performance. This intelligent machine allows you to set your brew time up to 24 hours in advance, ensuring your perfect cup is ready when you need it most. The thermal carafe keeps coffee hot for hours without a heating plate that can burn or alter the flavor, maintaining optimal taste from the first cup to the last. Brew strength control lets you customize the intensity to your preference, while the auto-shutoff feature provides peace of mind and energy efficiency. The large capacity brews up to 12 cups, perfect for families or entertaining guests. The removable water reservoir and permanent filter make filling and cleaning simple and convenient.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(9, '52bb49f4-f888-11f0-a10b-00163e1efc06', 'Running Shoes Men', 'Run faster run longer', 'Achieve your personal best with our Men\'s Running Shoes engineered for speed, comfort, and durability across all distances. These lightweight performance shoes feature responsive cushioning technology that absorbs impact and returns energy with each stride, reducing fatigue during long runs. The breathable engineered mesh upper provides excellent ventilation to keep your feet cool and dry while offering a secure, adaptive fit that moves with you. Strategic rubber placement on the outsole ensures optimal traction on various surfaces from pavement to trails. The supportive midsole promotes proper foot alignment and reduces the risk of injury. Reflective elements enhance visibility during early morning or evening runs. Whether you\'re training for a marathon or enjoying a casual jog, these shoes deliver the performance and comfort serious runners demand.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(10, '52bbdb75-f888-11f0-a10b-00163e1efc06', 'Laptop Backpack', 'Protect your tech', 'Safeguard your valuable technology with our Laptop Backpack designed for modern professionals, students, and travelers who demand both protection and organization. The padded laptop compartment safely accommodates devices up to 15.6 inches with shock-absorbing materials that cushion against bumps and drops. Multiple compartments and pockets keep your chargers, mouse, documents, water bottle, and personal items neatly organized and easily accessible. Constructed from durable water-resistant fabric with reinforced stitching, this backpack withstands daily wear and harsh weather conditions. Ergonomic padded shoulder straps and a breathable back panel ensure comfortable carrying even when fully loaded. A luggage strap on the back slides over rolling suitcase handles for convenient travel. The anti-theft hidden pocket keeps valuables secure while the USB charging port allows convenient device charging on the go.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(11, '52bc7e2c-f888-11f0-a10b-00163e1efc06', 'Electric Kettle', 'Quick and safe boiling', 'Streamline your morning routine with our Electric Kettle that combines rapid boiling performance with intelligent safety features for worry-free operation. This powerful 1500-watt kettle brings water to a rolling boil in just minutes, perfect for tea, coffee, instant meals, and more. Advanced auto-shutoff technology turns the kettle off immediately when water reaches boiling point or if it\'s accidentally switched on while empty, preventing damage and ensuring safety. The boil-dry protection sensor adds an extra layer of security. The large 1.7-liter capacity serves multiple cups without constant refilling, while the concealed heating element prevents mineral buildup for easier cleaning. The cordless design with 360-degree base allows convenient pouring from any angle. The built-in water level indicator ensures you always add the right amount, and the stay-cool handle provides safe, comfortable handling.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(12, '52bd09b2-f888-11f0-a10b-00163e1efc06', 'Wireless Mouse', 'Smooth and precise', 'Enhance your computing experience with our Ergonomic Wireless Mouse designed to provide exceptional comfort and precision during extended use. The contoured shape naturally fits your hand to reduce strain and prevent wrist fatigue, making it ideal for long work sessions or gaming marathons. Advanced optical tracking technology delivers pixel-perfect cursor control on virtually any surface with adjustable DPI settings for customized sensitivity. The reliable 2.4GHz wireless connection provides lag-free performance up to 30 feet away, eliminating tangled cables and desktop clutter. The energy-efficient design extends battery life up to 18 months on a single AA battery. Silent clicking technology reduces noise by up to 90 percent, perfect for quiet office environments. Plug-and-play USB nano receiver stores conveniently inside the mouse when not in use.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(13, '52bd9158-f888-11f0-a10b-00163e1efc06', 'Bath Towel Set', 'Soft and absorbent', 'Indulge in luxury every day with our Bath Towel Set crafted from premium 100% cotton that becomes softer and more absorbent with each wash. This complete set includes four generously sized towels: two bath towels, one hand towel, and one washcloth, providing everything you need for your bathroom. The plush 600 GSM weight offers exceptional thickness and absorbency that quickly wicks moisture away from your skin while remaining lightweight and quick-drying. Double-stitched hems ensure long-lasting durability that withstands frequent washing without fraying or fading. The elegant design complements any bathroom decor while the fade-resistant color stays vibrant wash after wash. Oeko-Tex certified materials guarantee these towels are free from harmful substances. Machine washable and dryer safe for easy care, these towels transform your daily routine into a spa-like experience.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(14, '52be1bfc-f888-11f0-a10b-00163e1efc06', 'Portable Charger 20000mAh', 'Never run out of power', 'Never worry about a dead battery again with our high-capacity 20000mAh Portable Charger that provides multiple full charges for your smartphones, tablets, and other USB devices. This powerful power bank features advanced fast-charging technology that delivers optimal charging speed for each connected device, getting you back to full battery up to 3 times faster than standard chargers. Dual USB output ports allow simultaneous charging of two devices, perfect for sharing with friends or powering multiple gadgets. The intelligent LED display shows remaining battery percentage so you always know when it\'s time to recharge. Built-in safety features protect against overcharging, overheating, and short circuits. The compact, portable design easily fits in bags or pockets, making it ideal for travel, commuting, camping, or emergency backup power. Compatible with all USB-charging devices.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(15, '52bea76d-f888-11f0-a10b-00163e1efc06', 'Indoor Plant Pot Set', 'Beautify your space', 'Bring life and natural beauty into your home with our Indoor Plant Pot Set featuring three elegant ceramic pots in complementary sizes perfect for creating stunning plant displays. Each handcrafted pot showcases a timeless design that enhances any interior decor from modern minimalist to classic traditional. The essential drainage holes in each pot prevent waterlogging and root rot, promoting healthy plant growth, while the included matching saucers protect your furniture from water damage. The smooth glazed finish is easy to clean and resistant to staining. Ideal for herbs, succulents, small flowers, or decorative foliage, these versatile pots work beautifully on windowsills, shelves, desks, or as a cohesive centerpiece arrangement. The neutral color palette complements any color scheme while the durable ceramic construction ensures years of use. Perfect for plant enthusiasts or as a thoughtful gift.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(16, '52bf388c-f888-11f0-a10b-00163e1efc06', 'Protein Powder Chocolate', 'Fuel your fitness', 'Power your workouts and recovery with our premium Whey Protein Powder in rich chocolate flavor that delivers 25 grams of high-quality protein per serving to support muscle growth and repair. This advanced formula uses fast-absorbing whey protein concentrate and isolate blend that your body can quickly utilize after intense training sessions. Each serving contains essential amino acids including BCAAs that are crucial for muscle protein synthesis and reducing exercise-induced muscle damage. The indulgent chocolate taste mixes smoothly without clumps in water, milk, or your favorite smoothie recipes, making post-workout nutrition something to look forward to. Low in sugar and fat while providing excellent nutritional value, this protein powder supports your fitness goals whether you\'re building muscle, losing weight, or maintaining a healthy lifestyle. Third-party tested for quality and purity.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(17, '52c02012-f888-11f0-a10b-00163e1efc06', 'Hardcover Journal', 'Capture your thoughts', 'Preserve your thoughts, dreams, and daily experiences in our Premium Hardcover Journal featuring high-quality construction that stands up to frequent use. This beautifully designed journal contains 200 lined pages made from thick, smooth paper that prevents ink bleed-through, making it perfect for fountain pens, gel pens, or pencils. The durable hardcover protects your writing while the lay-flat binding allows comfortable writing from the first page to the last without the book closing on you. An elastic closure band keeps your journal securely shut and protects your privacy, while the built-in ribbon bookmark helps you quickly find your place. The compact size fits easily in bags and backpacks for writing on the go. Perfect for journaling, goal setting, creative writing, travel documentation, or as a gratitude journal. The elegant design makes it a thoughtful gift for writers, students, and reflective thinkers.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(18, '52c0b2e6-f888-11f0-a10b-00163e1efc06', 'Kitchen Knife Set', 'Essential kitchen tools', 'Elevate your culinary skills with our professional-grade Kitchen Knife Set featuring eight precision-forged knives that handle every cutting task from delicate slicing to heavy chopping. This comprehensive collection includes a chef\'s knife, bread knife, carving knife, utility knife, paring knife, kitchen shears, knife sharpener, and a beautiful wooden storage block. Each blade is crafted from high-carbon stainless steel that maintains its razor-sharp edge through countless uses while resisting rust, corrosion, and discoloration. The ergonomically designed handles provide comfortable grip and excellent control, reducing hand fatigue during extended prep work. The full tang construction ensures perfect balance and durability. The included knife sharpener keeps your blades performing at their peak, while the elegant wooden block stores and displays your knives safely within easy reach. Perfect for home chefs and cooking enthusiasts.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(19, '52c13eb1-f888-11f0-a10b-00163e1efc06', 'Fleece Blanket Queen', 'Cozy comfort', 'Wrap yourself in warmth and comfort with our ultra-soft Fleece Blanket in queen size that transforms your bed or couch into a cozy haven. This luxurious blanket is crafted from premium microfiber fleece that feels incredibly soft against your skin while providing exceptional warmth without excessive weight. The generous queen dimensions provide ample coverage for sharing or wrapping yourself completely. Unlike traditional blankets that pill and shed, our high-quality fleece maintains its smooth texture and vibrant color even after repeated washing. Machine washable and dryer safe for easy care and maintenance, this blanket becomes even softer with each wash. Perfect for movie nights, reading in bed, outdoor events, or adding an extra layer of warmth on cold nights. The versatile design complements any bedroom or living room decor. Lightweight enough for year-round use yet warm enough for winter comfort.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(20, '52c1c78c-f888-11f0-a10b-00163e1efc06', 'Sunglasses Polarized', 'Protect your eyes', 'Shield your eyes in style with our Polarized Sunglasses featuring advanced UV400 lens technology that blocks 100% of harmful UVA and UVB rays while reducing glare from reflective surfaces. The polarized lenses dramatically improve visual clarity and reduce eye strain, making them perfect for driving, water sports, skiing, or any outdoor activities. Constructed with durable lightweight frames that withstand daily wear and active lifestyles, these sunglasses combine fashion with function. The scratch-resistant coating protects your lenses from damage, ensuring long-lasting clarity. The comfortable nose pads and temple tips provide a secure fit that stays in place during movement without pinching or slipping. Each pair comes with a protective hard case and cleaning cloth to keep your sunglasses in pristine condition. The timeless design suits all face shapes and complements any outfit from casual to sophisticated.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(21, '52c28d1e-f888-11f0-a10b-00163e1efc06', 'Air Fryer 5.8 Quart', 'Healthier frying', 'Revolutionize your cooking with our Digital Air Fryer that uses rapid air circulation technology to create crispy, delicious meals with up to 85% less fat than traditional deep frying. The spacious 5.8-quart capacity accommodates whole chickens, multiple servings of wings, or large batches of french fries, making it perfect for families or entertaining. Eight preset cooking programs take the guesswork out of preparing favorites like chicken, steak, fish, vegetables, and desserts with one-touch convenience. The intuitive digital touchscreen allows precise temperature control from 180°F to 400°F and cooking times up to 60 minutes. The non-stick basket and separator are dishwasher safe for effortless cleanup. The cool-touch exterior and automatic shutoff ensure safe operation. Enjoy guilt-free fried foods that taste amazing while supporting your health goals. Includes recipe book with delicious meal ideas.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(22, '52c31e21-f888-11f0-a10b-00163e1efc06', 'Gaming Mouse RGB', 'Level up your game', 'Dominate your competition with our high-performance Gaming Mouse featuring an advanced optical sensor with adjustable DPI up to 16,000 for pixel-precise accuracy and lightning-fast response times. This competitive-grade mouse is engineered for serious gamers who demand every advantage. Six programmable buttons can be customized with macros and complex commands through the intuitive software, giving you instant access to critical game functions. The customizable RGB lighting system offers millions of color combinations and dynamic effects that sync with your gaming setup. The ergonomic design with textured side grips ensures comfortable control during marathon gaming sessions while reducing hand fatigue. The ultra-durable switches are rated for 50 million clicks, and the braided cable prevents tangling and fraying. Onboard memory stores your profiles for consistent performance across different systems. Perfect for FPS, MOBA, MMO, and all competitive gaming.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(23, '52c3ef68-f888-11f0-a10b-00163e1efc06', 'Dumbbell Set Adjustable', 'Complete home gym', 'Transform any space into a complete home gym with our Adjustable Dumbbell Set that replaces 15 sets of traditional dumbbells while occupying minimal space. This innovative system allows rapid weight adjustment from 5 to 52.5 pounds per dumbbell with a simple turn of the dial, eliminating the need to manually change plates between exercises. Perfect for progressive resistance training, you can seamlessly increase weight as you build strength without interrupting your workout flow. The compact storage tray keeps your dumbbells organized and protects your floors when not in use. The durable construction features a combination of metal and high-impact plastic components engineered for longevity. Suitable for all fitness levels from beginners to advanced athletes, these dumbbells support hundreds of exercises targeting every muscle group. Save money and space while achieving your strength training goals with professional-quality equipment in the comfort of your home.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(24, '52c47c52-f888-11f0-a10b-00163e1efc06', 'Wall Art Canvas Set', 'Elevate your decor', 'Transform your living space with our stunning Wall Art Canvas Set featuring three coordinated panels that create a captivating focal point in any room. This modern abstract design brings sophistication and visual interest to your walls while complementing contemporary, minimalist, and transitional decor styles. Each canvas is professionally stretched over solid wooden frames that prevent warping and sagging, ensuring your artwork maintains its pristine appearance for years. The high-resolution printing process delivers vibrant colors and sharp details that capture every nuance of the original artwork. Pre-installed hanging hardware makes installation effortless, and the gallery-wrapped edges create a polished, frameless look that appears to float on your wall. Perfect for living rooms, bedrooms, offices, or dining areas, this versatile art set instantly elevates your interior design. The three-panel configuration allows creative arrangement options to suit your space perfectly.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(25, '52c505e0-f888-11f0-a10b-00163e1efc06', 'Mechanical Keyboard', 'Tactile typing experience', 'Experience superior typing performance with our RGB Mechanical Keyboard featuring genuine blue mechanical switches that deliver satisfying tactile feedback and an audible click with each keystroke. These premium switches are engineered for longevity with a 50-million keystroke lifespan while providing consistent actuation force and response. The full-size layout includes a number pad and dedicated media controls for convenient functionality. The aircraft-grade aluminum frame provides exceptional durability and stability that prevents keyboard flex during intense typing or gaming sessions. Customizable per-key RGB backlighting offers millions of color combinations and dynamic lighting effects controlled through intuitive software. The double-shot PBT keycaps resist shine and wear while maintaining their legends indefinitely. Anti-ghosting and N-key rollover ensure every keystroke registers accurately during rapid typing or complex gaming inputs. The braided USB cable and gold-plated connector ensure reliable connectivity. Perfect for programmers, writers, and gamers.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(26, '52c5926f-f888-11f0-a10b-00163e1efc06', 'Insulated Lunch Box', 'Fresh meals on the go', 'Keep your meals fresh and delicious throughout the day with our Insulated Lunch Box featuring advanced thermal insulation that maintains food temperature for hours whether hot or cold. This practical lunch solution includes multiple compartments that separate different foods, preventing flavors from mixing while keeping wet and dry items apart. The leakproof design uses secure zippered closures and sealed compartments that contain spills, making it safe to pack in bags without worry. Made from food-grade, BPA-free materials that are safe for your health and the environment. The included utensil set stores conveniently in a dedicated pocket, ensuring you\'re always prepared for meals. The adjustable shoulder strap and comfortable handle offer versatile carrying options for commuting, work, school, or outdoor activities. Easy to clean with a simple wipe-down, this lunch box promotes healthy eating habits by encouraging home-prepared meals while reducing waste from disposable packaging.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(27, '52c61f4d-f888-11f0-a10b-00163e1efc06', 'Resistance Bands Set', 'Versatile workout tool', 'Achieve a complete full-body workout anywhere with our Resistance Bands Set featuring five color-coded bands offering progressive resistance levels from light to extra heavy. This versatile fitness system enables hundreds of exercises targeting every major muscle group for strength training, rehabilitation, flexibility, and toning without expensive gym equipment or weights. The premium latex construction provides smooth, consistent resistance that won\'t snap or lose elasticity with regular use. Comfortable foam handles prevent slipping and reduce hand fatigue during intense workouts, while the door anchor allows secure attachment for door-based exercises. The ankle straps enable lower body exercises with proper form and control. Compact and lightweight, these bands fit easily in luggage or bags, making them perfect for home workouts, travel, or outdoor training. Suitable for all fitness levels with included exercise guide showing proper techniques and workout routines.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(28, '52c6aac3-f888-11f0-a10b-00163e1efc06', 'Floor Lamp Modern', 'Modern lighting solution', 'Illuminate your space with contemporary style using our Modern Floor Lamp that combines sleek design with practical functionality. This striking lamp features an adjustable head that pivots and tilts, allowing you to direct light precisely where needed for reading, working, or ambient lighting. The slim profile and minimalist aesthetic complement modern, industrial, and Scandinavian decor while the stable weighted base ensures it won\'t tip over. Energy-efficient LED technology provides bright, warm illumination that\'s easy on the eyes while consuming minimal electricity and eliminating the need for frequent bulb replacements. The convenient foot switch allows easy on/off control without bending down, perfect for bedside use. The durable metal construction ensures years of reliable performance. Ideal placement beside sofas, chairs, or beds creates the perfect reading nook while adding architectural interest to your room. Easy assembly with all necessary hardware included.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(29, '52c73cee-f888-11f0-a10b-00163e1efc06', 'Wireless Earbuds Pro', 'Premium sound quality', 'Immerse yourself in exceptional audio with our Wireless Earbuds Pro featuring advanced active noise cancellation that intelligently blocks ambient noise, creating a private listening sanctuary wherever you go. These premium earbuds deliver rich, balanced sound with deep bass, clear mids, and crisp highs that audiophiles appreciate. The ergonomic design with multiple ear tip sizes ensures a secure, comfortable fit that stays in place during workouts, commutes, or daily activities. Touch controls on each earbud provide intuitive operation for music playback, calls, and voice assistant access without reaching for your phone. The wireless charging case provides an additional 24 hours of battery life, and quick charge technology delivers hours of listening from just minutes of charging. Transparency mode lets you hear your surroundings when needed for safety and awareness. IPX4 water resistance protects against sweat and light rain, making these earbuds perfect for active lifestyles.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(30, '52c7ca21-f888-11f0-a10b-00163e1efc06', 'Cutting Board Bamboo', 'Eco-friendly kitchen essential', 'Enhance your food preparation with our Large Bamboo Cutting Board crafted from sustainable, fast-growing bamboo that\'s harder and more durable than traditional hardwoods yet gentle on knife blades. This spacious board provides ample workspace for chopping vegetables, slicing meats, or preparing elaborate meals with room to work efficiently. The integrated juice groove around the perimeter catches liquids from fruits, meats, and vegetables, keeping your countertops clean and preventing spills. Non-slip grips on the bottom secure the board firmly during use, ensuring safety while cutting. Bamboo\'s natural antimicrobial properties resist bacteria growth better than plastic or conventional wood cutting boards, promoting kitchen hygiene. The beautiful grain pattern adds natural elegance to your kitchen while the board doubles as an attractive serving platter for charcuterie, cheese, or bread. Easy to maintain with hand washing and occasional mineral oil treatment, this eco-friendly board will serve you for years.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(31, '52c85633-f888-11f0-a10b-00163e1efc06', 'Desk Organizer Set', 'Organize your workspace', 'Maximize productivity and minimize clutter with our Wooden Desk Organizer Set designed to keep all your office essentials neatly arranged and within easy reach. This comprehensive organization system features multiple compartments sized specifically for pens, pencils, markers, scissors, sticky notes, paper clips, and business cards. The natural wood construction adds warmth and sophistication to any workspace while the durable finish protects against scratches and stains. The thoughtful design maximizes vertical space, keeping your desk surface clear for working while ensuring frequently used items are immediately accessible. The sturdy construction prevents tipping even when fully loaded. Perfect for home offices, corporate workspaces, students, artists, or anyone seeking to create a more organized and efficient work environment. The timeless design complements any decor style from traditional to contemporary. Easy assembly with minimal tools required. Makes an excellent gift for professionals, teachers, or recent graduates setting up their workspace.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(32, '52c8eac8-f888-11f0-a10b-00163e1efc06', 'Electric Toothbrush', 'Superior oral care', 'Achieve professional-level oral care at home with our Rechargeable Electric Toothbrush that removes up to 100% more plaque than manual brushing for noticeably healthier gums and whiter teeth. This advanced toothbrush features three specialized brushing modes: daily clean, sensitive, and massage, allowing you to customize your oral care routine to your specific needs and comfort level. The built-in two-minute timer with 30-second interval alerts ensures you brush for the dentist-recommended duration while giving equal attention to each quadrant of your mouth. The pressure sensor protects your gums by alerting you if you\'re brushing too hard. The long-lasting rechargeable battery provides up to two weeks of use on a single charge, and the included travel case makes it perfect for trips. Replacement brush heads are readily available. The sleek, waterproof design is safe for use in the shower and easy to clean.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(33, '52c97a77-f888-11f0-a10b-00163e1efc06', 'Throw Pillow Set', 'Refresh your living space', 'Instantly refresh your living room or bedroom with our Decorative Throw Pillow Set featuring four coordinated pillow covers that effortlessly update your decor without the expense of new furniture. These versatile covers showcase modern patterns and textures that complement various design styles from bohemian to contemporary. The hidden zipper closures create a seamless, professional appearance while allowing easy removal for washing. Crafted from durable, fade-resistant fabric that maintains its vibrant colors and soft texture through countless washings. The standard 18x18-inch size fits most throw pillow inserts, which are sold separately or you can use existing inserts from old pillows. Perfect for sofas, beds, chairs, or window seats, these pillow covers add pops of color, pattern, and comfort throughout your home. Mix and match with solid colors or other patterns to create custom combinations. An affordable, impactful way to change your room\'s aesthetic with the seasons or your mood.', '2026-01-23 18:21:23', '2026-01-23 18:21:23'),
(34, '52ca06f0-f888-11f0-a10b-00163e1efc06', 'Digital Kitchen Scale', 'Accurate measurements', 'Achieve perfect results in every recipe with our Digital Kitchen Scale featuring precision weighing technology accurate to 0.1 ounce or 1 gram for baking, cooking, portion control, and meal prep. This essential kitchen tool helps you follow recipes exactly, ensuring consistent outcomes whether you\'re measuring flour for bread, portioning meat for meal prep, or tracking nutrition for health goals. The large LCD display shows measurements clearly in multiple units including ounces, pounds, grams, and milliliters. The convenient tare function allows you to zero out the weight of containers, measuring only the ingredients you add. The sleek, slim design stores easily in drawers, and the stainless steel platform cleans effortlessly with a simple wipe. The auto-off function conserves battery life, while the low battery and overload indicators prevent surprises. Maximum capacity of 11 pounds accommodates most cooking and baking needs. Essential for serious home cooks and health-conscious individuals.', '2026-01-23 18:21:23', '2026-01-23 18:21:23');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `wp_products`
--
ALTER TABLE `wp_products`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `product_id` (`product_id`),
  ADD KEY `idx_product_id` (`product_id`),
  ADD KEY `idx_product_name` (`product_name`);
ALTER TABLE `wp_products` ADD FULLTEXT KEY `fts_product_name` (`product_name`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `wp_products`
--
ALTER TABLE `wp_products`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
